name: Deploy Production
# on main branch updates
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
        #install serverless
      - name: Install Serverless Framework
        run: npm install -g serverless
        # authentication
      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY_DEPLOY }} --secret ${{ secrets.AWS_SECRET_DEPLOY }}
        # create ENV, use the shell `cat` command to create env.yml from secrets
      - name: Create env file
        run: |
          cat > .env << EOF
          ${{ secrets.ENV }}
          EOF
        #set environment variables
      - name: Set LD_PRELOAD
        run: sudo export LD_PRELOAD=/var/task/node_modules/canvas/build/Release/libz.so.1
        #install node modules
      - name: Install NPM dependencies
        run: npm install --production
        #install serverless offline
      - name: Install serverless-offline
        run: serverless plugin install -n serverless-offline
        #serverless deploy
      - name: Deploy
        run: sls deploy -s prod
